edulists/main/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required
import urllib3

from edulists import db
from edulists.models import User, Subject, Subscription
from edulists.forms import RegisterForm, LoginForm

http = urllib3.PoolManager()

main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
def index():
    if not current_user.is_anonymous:
        return redirect(url_for('main.subjects'))

    form = RegisterForm()

    if form.validate_on_submit():

        # create new user
        new_user = User(
            form.email.data,
            form.first_name.data.title(),
            form.last_name.data.title(),
            http.request('GET', 'http://ip.42.pl/raw').data.decode('utf-8'),
        )

        # create user password
        new_user.set_password(form.password.data)

        # add user to database
        db.session.add(new_user)
        db.session.commit()
        
        flash('MSG_REG', 'success')
        return redirect(url_for('main.index'))

    return render_template('main/index.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():

    # user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()

    if form.validate_on_submit():

        # log user in
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user, remember=form.remember_me.data)

        flash('You are now logged in.', 'success')
        return redirect(url_for('main.index'))

    return render_template('main/login.html', title='Login', form=form)

@main.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('main.index'))

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():

        new_user = User(
            form.email.data,
            form.first_name.data.title(),
            form.last_name.data.title(),
            http.request('GET', 'http://ip.42.pl/raw').data.decode('utf-8'),
        )

        new_user.set_password(form.password.data)

        db.session.add(new_user)
        db.session.commit()
        
        flash('MSG_REG', 'success')
        return redirect(url_for('main.register'))

    return render_template('main/register.html', title='Register', form=form)

@main.route('/subjects')
@login_required
def subjects():
    subjects = [sub.subject for sub in current_user.subscriptions]

    curriculums = [
        {
            'name': 'Australian Curriculum',
            'acronym': 'GEN',
            'region': 'AUS',
            'years': 'F-10',
        },
        {
            'name': 'Victorian Certificate of Education',
            'acronym': 'VCE',
            'region': 'VIC',
            'years': '11-12',
        },
        {
            'name': 'Higher School Certificate',
            'acronym': 'HSC',
            'region': 'NSW',
            'years': '11-12',
        },
        {
            'name': 'Queensland Certificate of Education',
            'acronym': 'QCE',
            'region': 'QLD',
            'years': '11-12',
        }
    ]

    return render_template('main/subjects.html', title='Subjects', subjects=subjects, curriculums=curriculums)

@main.route('/browse-subjects/<curriculum>')
@login_required
def browse_subjects(curriculum):
    subjects = Subject.query.filter_by(curriculum=curriculum).all()

    return render_template('main/browse_subjects.html', title='Browse Subjects', curriculum=curriculum, subjects=subjects)

@main.route('/subscribe/<subject_id>')
@login_required
def subscribe(subject_id):
    subject = Subject.query.get(subject_id)
    
    # create subscription
    new_subscription = Subscription(current_user.id, subject_id)
    db.session.add(new_subscription)
    db.session.commit()

    flash(f'You are now subscribed to "{subject.curriculum}: {subject.name}"', 'success')

    # redirect back to page
    return redirect(url_for('main.browse_subjects', curriculum=subject.curriculum))

@main.route('/unsubscribe/<subject_id>')
@login_required
def unsubscribe(subject_id):
    subject = Subject.query.get(subject_id)
    subscription = Subscription.query.filter_by(user_id=current_user.id).filter_by(subject_id=subject_id)

    # delete the subscription
    subscription.delete()
    db.session.commit()

    flash(f'You have unsubscribed to "{subject.curriculum}: {subject.name}"', 'success')

    return redirect(url_for('main.browse_subjects', curriculum=subject.curriculum))

@main.route('/unsubscribe-from-subjects-page/<subject_id>')
@login_required
def unsubscribe_from_subjects_page(subject_id):
    subject = Subject.query.get(subject_id)
    subscription = Subscription.query.filter_by(user_id=current_user.id).filter_by(subject_id=subject_id)

    # delete the subscription
    subscription.delete()
    db.session.commit()

    flash(f'You have unsubscribed to "{subject.curriculum}: {subject.name}"', 'success')

    return redirect(url_for('main.subjects'))
        

@main.route('/about')
def about():
    return render_template('main/about.html', title='About')

@main.route('/terms')
def terms():
    return render_template('main/terms.html', title='Terms of Service')

edulists/templates/main/_base.html
<!DOCTYPE html>
<html>

<head>
    <!-- META -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1">
    
    {% if title %}
        <title>EduLists Australia - {{ title }}</title>
    {% else %}
        <title>EduLists Australia</title>
    {% endif %}
    
    <!--  STYLESHEETS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/root.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <!-- FONTS / ICONS -->
    <script src="{{ url_for('static', filename='icons/js/all.js') }}"></script>

    <!-- SCRIPTS -->
    <script src="{{ url_for('static', filename='scripts/burger.js') }}"></script>
</head>

<body>
    <nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item title-navbar-item" href="{{ url_for('main.index') }}">
                <strong>EduLists</strong>&nbsp;Australia
            </a>
    
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
    
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ url_for('main.subjects') }}">
                    Subjects
                </a>
                <a class="navbar-item" href="{{ url_for('main.about') }}">
                    About
                </a>
            </div>
    
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if current_user.is_anonymous %}
                            <a class="button is-link" href="{{ url_for('main.register') }}">
                                <strong>Get Started</strong>
                            </a>
                            <a class="button is-light" href="{{ url_for('main.login') }}">
                                Log in
                            </a>
                        {% else %}
                            <a class="button is-light" href="{{ url_for('main.logout') }}">
                                Log out
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <br>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="notification is-{{ category }}" role="alert">
                    <button class="delete" onclick="window.location.href=window.location.href"></button>
                    {% if message == "MSG_REG" %}
                        You have been successfully registered! You can now <a href="{{ url_for('main.login') }}">log in</a>.
                    {% else %}
                        {{ message }}
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>

    {% block content %}{% endblock %}
</body>

</html>

edulists/templates/main/about.html
{% extends "main/_base.html" %}{% block content %}

<section class="section">
    <div class="container">
        [about]
    </div>
</section>

{% endblock %}

edulists/templates/main/browse_subjects.html
{% extends "main/_base.html" %}{% block content %}

<section class="section">
    <div class="container">
        <h1 class="title">
            Browse Subjects: {{ curriculum }}
        </h1>
        <h2 class="subtitle">
            Browse and subscribe to subjects in the {{ curriculum }}
        </h2>
        <p style="margin-bottom: 16px">
            <a href="{{ url_for('main.subjects') }}">
                <i class="fas fa-chevron-left"></i> Back to Your Subjects
            </a>
        </p>
        <div class="box">
            <table class="table is-fullwidth">
                <tr>
                    <th style="width:100%;">Subject Name</th>
                    <th>Subscribed</th>
                </tr>
                {% for subject in subjects %}
                    <tr>
                        {% if subject.has_subscriber(current_user.id) %}
                            <td><i class="fas fa-check" style="color: var(--success);"></i>&nbsp; {{ subject.name }}</td>
                            <td>
                                <a class="button is-small is-danger" href="{{ url_for('main.unsubscribe', subject_id=subject.id) }}">
                                    Unsubscribe
                                </a>
                            </td>
                        {% else %}
                            <td>{{ subject.name }}</td>
                            <td>
                                <a class="button is-small is-success is-fullwidth" href="{{ url_for('main.subscribe', subject_id=subject.id) }}">
                                    Subscribe
                                </a>
                            </td>
                        {% endif %}
                        
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</section>

{% endblock %}

edulists/templates/main/index.html
{% extends "main/_base.html" %}{% block content %}

<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-three-fifths">
                <section class="section">
                    <h1 class="title">
                        Connecting Australian Teachers
                    </h1>
                    <h2 class="subtitle">
                        EduLists makes it easy to share ideas with other teachers.
                    </h2>
                </section>
            </div>
            <div class="column">
                <div class="box">
                    <div>
                        <strong>Get started with EduLists</strong>
                    </div>
                    <br>
                    <form action="" method="post">
                        {{ form.csrf_token }}

                        <!-- NAME FIELDS -->
                        <div class="field-body" style="margin-bottom: 12px;">
                            <div class="field">
                                {% if not form.first_name.errors %}
                                <p class="control has-icons-left">
                                    {{ form.first_name(class="input", type="text", placeholder="First Name") }}
                                    <span class="icon is-small is-left">
                                        <i class="fas fa-user"></i>
                                    </span>
                                </p>
                                {% else %}
                                <p class="control has-icons-left has-icons-right">
                                    {{ form.first_name(class="input is-danger", type="text", placeholder="First Name") }}
                                    <span class="icon is-small is-left">
                                        <i class="fas fa-user"></i>
                                    </span>
                                    <span class="icon is-small is-right">
                                        <i class="fas fa-exclamation-triangle"></i>
                                    </span>
                                    {% for error in form.first_name.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                </p>
                                {% endif %}
                            </div>
                            <div class="field">
                                {% if not form.last_name.errors %}
                                <p class="control has-icons-left">
                                    {{ form.last_name(class="input", type="text", placeholder="Last Name") }}
                                    <span class="icon is-small is-left">
                                        <i class="fas fa-user"></i>
                                    </span>
                                </p>
                                {% else %}
                                <p class="control has-icons-left has-icons-right">
                                    {{ form.last_name(class="input is-danger", type="text", placeholder="Last Name") }}
                                    <span class="icon is-small is-left">
                                        <i class="fas fa-user"></i>
                                    </span>
                                    <span class="icon is-small is-right">
                                        <i class="fas fa-exclamation-triangle"></i>
                                    </span>
                                    {% for error in form.last_name.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                </p>
                                {% endif %}
                            </div>
                        </div>

                        <!-- EMAIL FIELD -->
                        <div class="field">
                            {% if not form.email.errors %}
                            <p class="control has-icons-left">
                                {{ form.email(class="input", type="email", placeholder="School Email") }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-envelope"></i>
                                </span>
                            </p>
                            {% else %}
                            <p class="control has-icons-left has-icons-right">
                                {{ form.email(class="input is-danger", type="email", placeholder="School Email") }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-envelope"></i>
                                </span>
                                <span class="icon is-small is-right">
                                    <i class="fas fa-exclamation-triangle"></i>
                                </span>
                                {% for error in form.email.errors %}
                                <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            </p>
                            {% endif %}
                        </div>

                        <!-- PASSWORD FIELD -->
                        <div class="field">
                            {% if not form.password.errors %}
                            <p class="control has-icons-left">
                                {{ form.password(class="input", type="password", placeholder="Password") }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-lock"></i>
                                </span>
                            </p>
                            {% else %}
                            <p class="control has-icons-left has-icons-right">
                                {{ form.password(class="input is-danger", type="password", placeholder="Password") }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-lock"></i>
                                </span>
                                <span class="icon is-small is-right">
                                    <i class="fas fa-exclamation-triangle"></i>
                                </span>
                                {% for error in form.password.errors %}
                                <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            </p>
                            {% endif %}
                        </div>

                        <!-- ACCEPT TOS FIELD -->
                        <div class="field">
                            <p class="control">
                                <label class="checkbox">
                                    {{ form.accept_tos(type="checkbox") }}
                                    I agree to the <a href="{{ url_for('main.terms') }}">terms and conditions</a>
                                </label>
                            </p>
                        </div>

                        <div class="field">
                            {{ form.submit(class="button is-link") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="hero is-light">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">
                Using a network of automated mailing lists, EduLists makes it easy to stay up-to-date on how other
                educators
                in your state teach your subjects, letting you learn more about how you can improve and help your
                students.
            </h2>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="box">
                    <p class="title is-5"><i class="fas fa-user"></i> Create a teacher account</p>
                    <div class="sample-illustration">sample illustration</div>
                </div>
            </div>
            <div class="column">
                <div class="box">
                    <p class="title is-5"><i class="fas fa-pencil-alt"></i> Subscribe to your subjects</p>
                    <div class="sample-illustration">sample illustration</div>
                </div>
            </div>
            <div class="column">
                <div class="box">
                    <p class="title is-5"><i class="fas fa-comments"></i> Share and collaborate</p>
                    <div class="sample-illustration">sample illustration</div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

edulists/templates/main/register.html
{% extends "main/_base.html" %}{% block content %}

<section class="section">
    <div class="container" style="max-width: 420px;">
        <div class="box">
            <div>
                <strong>Get started with EduLists</strong>
            </div>
            <br>
            <form action="" method="post">
                {{ form.csrf_token }}

                <!-- NAME FIELDS -->
                <div class="field-body" style="margin-bottom: 12px;">
                    <div class="field">
                        {% if not form.first_name.errors %}
                        <p class="control has-icons-left">
                            {{ form.first_name(class="input", type="text", placeholder="First Name") }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-user"></i>
                            </span>
                        </p>
                        {% else %}
                        <p class="control has-icons-left has-icons-right">
                            {{ form.first_name(class="input is-danger", type="text", placeholder="First Name") }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-user"></i>
                            </span>
                            <span class="icon is-small is-right">
                                <i class="fas fa-exclamation-triangle"></i>
                            </span>
                            {% for error in form.first_name.errors %}
                            <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </p>
                        {% endif %}
                    </div>
                    <div class="field">
                        {% if not form.last_name.errors %}
                        <p class="control has-icons-left">
                            {{ form.last_name(class="input", type="text", placeholder="Last Name") }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-user"></i>
                            </span>
                        </p>
                        {% else %}
                        <p class="control has-icons-left has-icons-right">
                            {{ form.last_name(class="input is-danger", type="text", placeholder="Last Name") }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-user"></i>
                            </span>
                            <span class="icon is-small is-right">
                                <i class="fas fa-exclamation-triangle"></i>
                            </span>
                            {% for error in form.last_name.errors %}
                            <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </p>
                        {% endif %}
                    </div>
                </div>

                <!-- EMAIL FIELD -->
                <div class="field">
                    {% if not form.email.errors %}
                    <p class="control has-icons-left">
                        {{ form.email(class="input", type="email", placeholder="School Email") }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </p>
                    {% else %}
                    <p class="control has-icons-left has-icons-right">
                        {{ form.email(class="input is-danger", type="email", placeholder="School Email") }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fas fa-exclamation-triangle"></i>
                        </span>
                        {% for error in form.email.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endif %}
                </div>

                <!-- PASSWORD FIELD -->
                <div class="field">
                    {% if not form.password.errors %}
                    <p class="control has-icons-left">
                        {{ form.password(class="input", type="password", placeholder="Password") }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                    </p>
                    {% else %}
                    <p class="control has-icons-left has-icons-right">
                        {{ form.password(class="input is-danger", type="password", placeholder="Password") }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fas fa-exclamation-triangle"></i>
                        </span>
                        {% for error in form.password.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endif %}
                </div>

                <!-- ACCEPT TOS FIELD -->
                <div class="field">
                    <p class="control">
                        <label class="checkbox">
                            {{ form.accept_tos(type="checkbox") }}
                            I agree to the <a href="{{ url_for('main.terms') }}">terms and conditions</a>
                        </label>
                    </p>
                </div>

                <div class="field">
                    {{ form.submit(class="button is-link") }}
                </div>
                <div>
                    Already have an account? <a href="{{ url_for('main.login') }}">Log in</a>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock %}

edulists/templates/main/subjects.html
{% extends "main/_base.html" %}{% block content %}

<section class="section">
    <div class="container">
        <h1 class="title">
            Your Subjects
        </h1>
        <h2 class="subtitle">
            These are the subjects that you are subscribed to
        </h2>
        <div class="box">
            {% if subjects %}
                <table class="table is-fullwidth">
                    <tr>
                        <th style="width:100%;">Subject Name</th>
                        <th>Subscribed</th>
                    </tr>
                    {% for subject in subjects %}
                        <tr>
                            <td>
                                <i class="fas fa-check" style="color: var(--success);"></i>&nbsp; {{ subject.curriculum }}: {{ subject.name }}
                                <br>
                                <span class="tag is-light">
                                    <i class="fas fa-tag" style="color: gray;"></i>&nbsp; {{ subject.address }}
                                </span>
                            </td>
                            <td>
                                <a class="button is-outlined is-small is-danger" href="{{ url_for('main.unsubscribe_from_subjects_page', subject_id=subject.id) }}">
                                    Unsubscribe
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <div style="text-align: center; color: gray;">
                    <i>You have not subscribed to any subjects yet.</i>
                </div>
            {% endif %}
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <h1 class="title">
            Browse Subjects
        </h1>
        <h2 class="subtitle">
            Select your curriculum and browse subjects
        </h2>
        <div class="box">
            <table class="table is-fullwidth">
                <tr>
                    <th style="width:100%;">Curriculum Name</th>
                    <th>Region</th>
                    <th>Years</th>
                </tr>
                {% for curriculum in curriculums %}
                    <tr>
                        <td><i class="fas fa-scroll " style="color: var(--accent);"></i>&nbsp; <a href="{{ url_for('main.browse_subjects', curriculum=curriculum.acronym) }}">{{ curriculum.name }} ({{ curriculum.acronym }})</a></td>
                        <td>{{ curriculum.region }}</td>
                        <td>{{ curriculum.years }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</section>

{% endblock %}